apiVersion: v1
kind: Service
metadata:
  name: workshop-organizer-app-service
spec:
  selector:
    app: workshop-organizer-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
